import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const a=require('../site/lib/attack-model.js');

test('ATT&CK v19.2 model pins all three current domains and source counts',()=>{const m=a.model();assert.equal(m.version,'v19.2');assert.equal(m.domains.enterprise.tactics,15);assert.equal(m.domains.enterprise.techniques,222);assert.equal(m.domains.enterprise.subtechniques,475);assert.equal(m.domains.mobile.techniques,77);assert.equal(m.domains.ics.techniques,79);assert.equal(m.semantics.free_text_auto_classification,false);assert.equal(m.semantics.automatic_actor_attribution,false);});

test('Enterprise matrix includes v19.2 Stealth and Defense Impairment tactics',()=>{const c=a.catalog({domain:'enterprise',include:'tactics'});const by=Object.fromEntries(c.tactics.map(x=>[x.id,x.name]));assert.equal(by.TA0005,'Stealth');assert.equal(by.TA0112,'Defense Impairment');assert.deepEqual(a.ENTERPRISE_MATRIX_ORDER.slice(0,2),['TA0043','TA0042']);});

test('exact resolver accepts IDs and exact names but not prose or retired selectors',()=>{const x=a.resolve({domain:'enterprise',refs:['T1059.001','OS Credential Dumping','PowerShell execution seen in telemetry','T1562.001']});assert.equal(x.resolved.length,2);assert.deepEqual(x.resolved.map(r=>r.record.id).sort(),['T1003','T1059.001']);assert.deepEqual(x.unresolved,['PowerShell execution seen in telemetry','T1562.001']);assert.match(x.selector_policy,/exact/i);});

test('behavior normalization enriches explicit technique with official tactic and parentage',()=>{const b=a.normalizeBehavior({behavior_id:'b1',domain:'enterprise',technique_refs:['T1059.001'],status:'observed',evidence_refs:['fixture:1']});assert.equal(b.techniques[0].id,'T1059.001');assert.equal(b.techniques[0].parent_id,'T1059');assert.deepEqual(b.techniques[0].tactic_ids,['TA0002']);assert.deepEqual(b.official_tactics_from_techniques.map(x=>x.id),['TA0002']);assert.equal(b.semantics.no_free_text_classification,true);});

test('behavior normalization refuses unresolved selectors rather than guessing',()=>assert.throws(()=>a.normalizeBehavior({domain:'enterprise',technique_refs:['credential dumping maybe']}),/Unresolved ATT&CK selector/));

test('coverage distinguishes missing detection evidence from a negative claim',()=>{const b=a.normalizeBehavior({behavior_id:'cred',domain:'enterprise',technique_refs:['T1003.001'],status:'observed'});const c=a.coverage({domain:'enterprise',behaviors:[b],detections:[]});assert.deepEqual(c.no_detection_evidence_for_observed_techniques,['T1003.001']);assert.equal(c.semantics.missing_detection_evidence_is_unknown_not_proof_of_no_detection,true);assert.equal(c.semantics.no_weighted_score,true);});

test('supplied detection evidence attaches only to explicit technique refs',()=>{const c=a.coverage({domain:'enterprise',behaviors:[{behavior_id:'exec',technique_refs:['T1059.001'],status:'observed'}],detections:[{id:'det-1',technique_refs:['T1059.001'],status:'covered',evidence_refs:['fixture:detection']}]});assert.equal(c.technique_coverage[0].detection_evidence_supplied,true);assert.deepEqual(c.technique_coverage[0].statuses,['covered']);assert.deepEqual(c.no_detection_evidence_for_observed_techniques,[]);});

test('cross-model composition requires explicit known bindings',()=>{const b={behavior_id:'b1',domain:'enterprise',technique_refs:['T1059.001'],status:'observed'};const x=a.compose({domain:'enterprise',behaviors:[b],diamond_events:[{event_id:'e1',capability:'PowerShell'}],pyramid_indicators:[{indicator_id:'i1',indicator_type:'ttp',status:'detected'}],ukc_bindings:[{behavior_id:'b1',ukc_phase_refs:['Execution']}],diamond_bindings:[{behavior_id:'b1',event_id:'e1'}],pyramid_bindings:[{behavior_id:'b1',indicator_id:'i1'}]});assert.equal(x.ukc_bindings.length,1);assert.equal(x.diamond_bindings.length,1);assert.equal(x.pyramid_bindings.length,1);assert.equal(x.semantics.all_cross_model_bindings_explicit_only,true);assert.throws(()=>a.compose({domain:'enterprise',behaviors:[b],diamond_bindings:[{behavior_id:'b1',event_id:'missing'}]}),/unknown event/i);});

test('public ATT&CK API exposes model and pure behavior actions',async()=>{const handler=require('../site/api/v1/attack.js');const invoke=req=>new Promise(resolve=>{const res={setHeader(){},status(c){this.code=c;return this},json(x){resolve({code:this.code||200,body:x})}};handler(req,res)});const m=await invoke({method:'GET'});assert.equal(m.code,200);assert.equal(m.body.version,'v19.2');const b=await invoke({method:'POST',body:{action:'normalize_behavior',behavior:{domain:'enterprise',technique_refs:['T1059.001'],status:'observed'}}});assert.equal(b.code,200);assert.equal(b.body.contract,'shatteredcastles.attack.behavior.v1');});
