import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url),d=require('../site/lib/d3fend-model.js');

test('D3FEND 1.6.0 model pins ontology, tactics, techniques, and inferred mapping provenance',()=>{const m=d.model();assert.equal(m.version,'1.6.0');assert.equal(m.counts.defensive_tactics,7);assert.equal(m.counts.top_level_technique_families,30);assert.equal(m.counts.defensive_techniques,271);assert.equal(m.source.ontology_ttl.sha256,'4909a5bb66b75d2c359624398848936fb56a6b246bcd5cfcd277977a1277753a');assert.equal(m.source.mapping_attack_version,'v19.0');assert.equal(m.composition.attack.current_version,'v19.2');assert.equal(m.semantics.full_mappings_are_inferred_relationships,true);});

test('D3FEND tactic order preserves ontology display order',()=>{const m=d.model();assert.deepEqual(m.tactics.map(x=>x.name),['Model','Harden','Detect','Isolate','Deceive','Evict','Restore']);});

test('exact resolver accepts D3FEND ID/name but not free text',()=>{const r=d.resolve({refs:['D3-ABPI','Application-based Process Isolation','isolate suspicious powershell somehow']});assert.equal(r.resolved.length,2);assert.deepEqual(r.resolved.map(x=>x.record.id),['D3-ABPI','D3-ABPI']);assert.deepEqual(r.unresolved,['isolate suspicious powershell somehow']);});

test('defense normalization preserves explicit status without claiming effectiveness',()=>{const x=d.normalizeDefense({defense_id:'def1',technique_refs:['D3-ABPI'],status:'implemented',evidence_refs:['fixture:defense']});assert.equal(x.techniques[0].id,'D3-ABPI');assert.deepEqual(x.techniques[0].tactics,['Isolate']);assert.equal(x.status,'implemented');assert.equal(x.semantics.implementation_does_not_imply_effectiveness,true);});

test('ATT&CK mapping returns D3FEND inferred candidates for exact current ID',()=>{const x=d.mapAttack({domain:'enterprise',attack_refs:['T1003.001']});assert.equal(x.attack_mappings[0].attack_id,'T1003.001');assert.ok(x.attack_mappings[0].candidate_count>=10);assert.ok(x.attack_mappings[0].candidates.some(c=>c.d3fend_id==='D3-ABPI'));assert.equal(x.semantics.relationships_are_d3fend_inferred,true);assert.equal(x.mapping_source.attack_version,'v19.0');});

test('mapping bridge refuses retired/non-current ATT&CK selector even if D3FEND source contains it',()=>assert.throws(()=>d.mapAttack({domain:'enterprise',attack_refs:['T1562.001']}),/Unresolved current ATT&CK selector/));

test('Mobile mapping absence remains explicit unknown rather than fabricated coverage',()=>{const x=d.mapAttack({domain:'mobile',attack_refs:['T1409']});assert.equal(x.attack_mappings[0].candidate_count,0);assert.deepEqual(x.unmapped_current_attack_ids,['T1409']);assert.equal(x.semantics.missing_mapping_is_unknown_not_no_countermeasure,true);});

test('alignment reports inferred candidate overlap without treating it as coverage proof',()=>{const x=d.alignment({domain:'enterprise',behaviors:[{behavior_id:'b1',technique_refs:['T1003.001'],status:'observed'}],defenses:[{defense_id:'def1',technique_refs:['D3-ABPI'],status:'implemented'}]});assert.equal(x.attack_alignment[0].explicit_overlap_present,true);assert.equal(x.attack_alignment[0].explicit_defense_overlap[0].d3fend_id,'D3-ABPI');assert.equal(x.semantics.inferred_candidate_overlap_is_not_coverage_proof,true);assert.equal(x.semantics.no_weighted_score,true);});

test('composition requires explicit selected binding and verifies inferred basis',()=>{const x=d.compose({domain:'enterprise',behaviors:[{behavior_id:'b1',technique_refs:['T1003.001'],status:'observed'}],defenses:[{defense_id:'def1',technique_refs:['D3-ABPI'],status:'planned'}],attack_defense_bindings:[{behavior_id:'b1',defense_id:'def1',basis:'d3fend_inferred'}]});assert.equal(x.attack_defense_bindings.length,1);assert.deepEqual(x.attack_defense_bindings[0].candidate_pairs,[{attack_id:'T1003.001',d3fend_id:'D3-ABPI'}]);assert.equal(x.semantics.bindings_explicit_only,true);assert.throws(()=>d.compose({domain:'enterprise',behaviors:[{behavior_id:'b1',technique_refs:['T1003.001']}],defenses:[{defense_id:'def1',technique_refs:['D3-AA']}],attack_defense_bindings:[{behavior_id:'b1',defense_id:'def1',basis:'d3fend_inferred'}]}),/no exact inferred candidate pair/i);});

test('public D3FEND API exposes pure model and mapping actions',async()=>{const handler=require('../site/api/v1/d3fend.js');const invoke=req=>new Promise(resolve=>{const res={setHeader(){},status(c){this.code=c;return this},json(x){resolve({code:this.code||200,body:x})}};handler(req,res)});const m=await invoke({method:'GET'});assert.equal(m.code,200);assert.equal(m.body.version,'1.6.0');const x=await invoke({method:'POST',body:{action:'map_attack',mapping:{domain:'enterprise',attack_refs:['T1003.001']}}});assert.equal(x.code,200);assert.equal(x.body.contract,'shatteredcastles.d3fend.attack-map.v1');});
