import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const d=require('../site/lib/dml-model.js');

test('original Stillions DML preserves levels 0 through 8 without later Identity extension',()=>{const m=d.model();assert.equal(m.levels.length,9);assert.deepEqual(m.levels.map(x=>x.name),['None or Unknown','Atomic Indicators','Host & Network Artifacts','Tools','Procedures','Techniques','Tactics','Strategy','Goals']);assert.equal(m.semantics.original_levels_0_through_8,true);assert.equal(m.semantics.later_identity_extension_excluded,true);assert.equal(m.semantics.detection_not_prevention,true);});

test('DML level must be explicit and is never inferred from free text',()=>{assert.throws(()=>d.normalizeDetection({id:'x',notes:'detects tactics'}),/level must be explicit/i);const x=d.normalizeDetection({id:'x',dml_level:5,status:'designed'});assert.equal(x.dml_id,'DML-5');assert.equal(x.dml_name,'Techniques');assert.equal(x.demonstrated,false);});

test('demonstrated detection requires consume detect and act evidence plus validated or deployed status',()=>{const base={id:'det',dml_level:5,scope_type:'analytic',can_consume:true,can_act:true,consume_evidence_refs:['intel:test'],detection_evidence_refs:['test:hit'],action_evidence_refs:['runbook:test']};assert.equal(d.normalizeDetection({...base,status:'tested'}).demonstrated,false);assert.equal(d.normalizeDetection({...base,status:'validated'}).demonstrated,true);assert.equal(d.normalizeDetection({...base,status:'deployed'}).demonstrated,true);assert.equal(d.normalizeDetection({...base,status:'validated',action_evidence_refs:[]}).demonstrated,false);});

test('assessment reports only input-bound highest demonstrated level and is not cumulative',()=>{const a=d.assessment({scope_type:'program',scope_ref:'fixture',detections:[{id:'d1',dml_level:1,status:'deployed',can_consume:true,can_act:true,consume_evidence_refs:['c1'],detection_evidence_refs:['d1'],action_evidence_refs:['a1']},{id:'d5',dml_level:5,status:'validated',can_consume:true,can_act:true,consume_evidence_refs:['c5'],detection_evidence_refs:['d5'],action_evidence_refs:['a5']},{id:'d6',dml_level:6,status:'designed'}]});assert.equal(a.highest_present_level,6);assert.equal(a.highest_demonstrated_level,5);assert.deepEqual(a.demonstrated_levels,[1,5]);assert.deepEqual(a.undemonstrated_present_levels,[6]);assert.equal(a.semantics.not_cumulative,true);assert.equal(a.semantics.higher_level_does_not_imply_lower_level_coverage,true);});

test('ATT&CK semantic bridge returns candidate DML level but does not assign maturity',()=>{const b=d.semanticBridge({source:'attack',domain:'enterprise',refs:['T1059.001','TA0002','PowerShell behavior maybe']});assert.equal(b.results.length,2);assert.deepEqual(b.results.find(x=>x.source_id==='T1059.001').candidate_dml_levels,[5]);assert.deepEqual(b.results.find(x=>x.source_id==='TA0002').candidate_dml_levels,[6]);assert.deepEqual(b.unresolved,['PowerShell behavior maybe']);assert.equal(b.semantics.candidate_levels_only,true);assert.equal(b.semantics.no_maturity_claim,true);});

test('Pyramid semantic bridge preserves ambiguous TTP span instead of flattening it',()=>{const b=d.semanticBridge({source:'pyramid',refs:['hash','network_artifact','tool','ttp']});assert.deepEqual(b.results.map(x=>x.candidate_dml_levels),[[1],[2],[3],[4,5,6]]);assert.match(b.results.at(-1).mapping_semantics,/ambiguous/i);});

test('composition requires explicit bindings and never changes detection level',()=>{const x=d.compose({detections:[{id:'d5',dml_level:5,status:'validated',can_consume:true,can_act:true,consume_evidence_refs:['c'],detection_evidence_refs:['d'],action_evidence_refs:['a']}],bindings:[{detection_id:'d5',target_type:'attack_technique',target_ref:'T1059.001',evidence_refs:['bind:1']}]});assert.equal(x.bindings.length,1);assert.equal(x.bindings[0].explicit,true);assert.equal(x.detections[0].dml_level,5);assert.equal(x.semantics.binding_does_not_assign_dml_level,true);assert.throws(()=>d.compose({detections:[{id:'d1',dml_level:1}],bindings:[{detection_id:'missing',target_type:'attack_technique',target_ref:'T1059.001'}]}),/unknown detection/i);});

test('organization scope is not silently inferred from a rule or program assessment',()=>{const a=d.assessment({scope_type:'analytic',scope_ref:'det-1',detections:[{id:'d8',dml_level:8,status:'deployed',can_consume:true,can_act:true,consume_evidence_refs:['c'],detection_evidence_refs:['d'],action_evidence_refs:['a']}]});assert.equal(a.highest_demonstrated_level,8);assert.equal(a.scope_type,'analytic');assert.equal(a.semantics.not_organization_wide_unless_scope_type_is_organization,true);});

test('public DML API exposes deterministic pure actions',async()=>{const handler=require('../site/api/v1/dml.js');const invoke=req=>new Promise(resolve=>{const res={setHeader(){},status(c){this.code=c;return this},json(x){resolve({code:this.code||200,body:x})}};handler(req,res)});const m=await invoke({method:'GET'});assert.equal(m.code,200);assert.equal(m.body.contract,'shatteredcastles.dml.model.v1');const x=await invoke({method:'POST',body:{action:'normalize_detection',detection:{id:'api',dml_level:2,status:'tested'}}});assert.equal(x.code,200);assert.equal(x.body.dml_id,'DML-2');});
